### PR TITLE
[MPLUGINTESTING-80] Upgrade to maven 4.0.0-alpha-4

### PR DESCRIPTION
**Pull request by gnodet**
- [MPLUGINTESTING-80] Upgrade to maven 4.0.0-alpha-4

### CODE REVIEW

**Comment by michael-o** [comment]
Is this still backward compatible?

**Comment by gnodet** [comment]
> Is this still backward compatible?

The upgrade from 4.0.0-alpha-2 to alpha-4 ? The renaming from `Dom` to `XmlNode` is definitely not, but that's why they are alpha releases.

If you're asking about the upgrade from 3 to 4, that was done in https://github.com/apache/maven-plugin-testing/pull/24, the  change should be compatible as the v4 api is supported through new classes in a different package https://github.com/apache/maven-plugin-testing/tree/master/maven-plugin-testing-harness/src/main/java/org/apache/maven/api/plugin/testing

**Comment by gnodet** [comment]
> > Is this still backward compatible?
> 
> The upgrade from 4.0.0-alpha-2 to alpha-4 ? The renaming from `Dom` to `XmlNode` is definitely not, but that's why they are alpha releases.
> 
> If you're asking about the upgrade from 3 to 4, that was done in #24, the change should be compatible as the v4 api is supported through new classes in a different package https://github.com/apache/maven-plugin-testing/tree/master/maven-plugin-testing-harness/src/main/java/org/apache/maven/api/plugin/testing Also, the version has been updated to `4.0.0-SNAPSHOT` in the PR above

I'm planning a `4.0.0-alpha-1` release, as there may be a few iterations while we work on various plugins.

**Comment by michael-o** [comment]
> > Is this still backward compatible?
> 
> The upgrade from 4.0.0-alpha-2 to alpha-4 ? The renaming from `Dom` to `XmlNode` is definitely not, but that's why they are alpha releases.
> 
> If you're asking about the upgrade from 3 to 4, that was done in #24, the change should be compatible as the v4 api is supported through new classes in a different package https://github.com/apache/maven-plugin-testing/tree/master/maven-plugin-testing-harness/src/main/java/org/apache/maven/api/plugin/testing Also, the version has been updated to `4.0.0-SNAPSHOT` in the PR above

Yes, my bad. I did not pay attention to it.

**Review by michael-o — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #181

**Pull request merged**
